name: Clone Workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clone Workflow
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: | 
          cd ../pub 
          git clone https://github.com/leonelasantos/leonelasantos.github.io.git